/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AChart: typeof import('./../components/Charts/AChart.vue')['default']
    BaseMapSwitch: typeof import('./../components/BaseMapSwitch.vue')['default']
    BChart: typeof import('./../components/Charts/BChart.vue')['default']
    CChart: typeof import('./../components/Charts/CChart.vue')['default']
    DChart: typeof import('./../components/Charts/DChart.vue')['default']
    EChart: typeof import('./../components/Charts/EChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FChart: typeof import('./../components/Charts/FChart.vue')['default']
    GChart: typeof import('./../components/Charts/GChart.vue')['default']
    HChart: typeof import('./../components/Charts/HChart.vue')['default']
    IChart: typeof import('./../components/Charts/IChart.vue')['default']
    IconSvgCamera: typeof import('~icons/svg/camera')['default']
    IconSvgCheckin: typeof import('~icons/svg/checkin')['default']
    IconSvgFloor: typeof import('~icons/svg/floor')['default']
    IconSvgGeoanalysis: typeof import('~icons/svg/geoanalysis')['default']
    IconSvgHeatmap: typeof import('~icons/svg/heatmap')['default']
    IconSvgLaw: typeof import('~icons/svg/law')['default']
    IconSvgLift: typeof import('~icons/svg/lift')['default']
    IconSvgNavline: typeof import('~icons/svg/navline')['default']
    IconSvgPipeline: typeof import('~icons/svg/pipeline')['default']
    IconSvgResource: typeof import('~icons/svg/resource')['default']
    IconSvgSpecialequipment: typeof import('~icons/svg/specialequipment')['default']
    IconSvgTree: typeof import('~icons/svg/tree')['default']
    JChart: typeof import('./../components/Charts/JChart.vue')['default']
    KChart: typeof import('./../components/Charts/KChart.vue')['default']
    LChart: typeof import('./../components/Charts/LChart.vue')['default']
    Measure: typeof import('./../components/SMapControls/Measure.vue')['default']
    Navigation: typeof import('./../components/SMapControls/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SBaseMap: typeof import('./../components/SBaseMap.vue')['default']
    SChart: typeof import('./../components/SChart.vue')['default']
    SMapLocation: typeof import('./../components/SMapControls/SMapLocation.vue')['default']
    SMapScene: typeof import('./../components/SMapControls/SMapScene.vue')['default']
    SPopup: typeof import('./../components/SPopup.vue')['default']
    STitleContentPanel: typeof import('./../components/STitleContentPanel.vue')['default']
    STitlePopup: typeof import('./../components/STitlePopup.vue')['default']
  }
}
